### ISSUE TITLE
#portlet-left0 shows a blank page

### ISSUE THREAD

**Issue by icarrara** [marcoscv-work/traveler-theme#1]
Trying to use traveler-theme I'm getting the below issue:

Only when the user is not logged, the Home page and all the pages addressed with the url  #portlet-left0 shows a blank page

I double-checked all pages, journal articles, images and all items have "Guest" permission.

Marcos, please could you help me ?

Thank you in advance !
Ivano C.

**Comment by marcoscv-work** [comment]
Hi @icarrara , what Liferay version are you using?

Sounds like a resources importer bug.

**Comment by icarrara** [comment]
Hello @marcoscv-work ! Thank you for your reply

I'm using Liferay Portal Community Edition 6.2 CE GA4 (Newton / Build 6203 / April 16, 2015) and I'm trying to install Traveler Theme directly from Control Panel and Marketplace.

In fact I found the below errors about resources importer - below the Tomcat's log fragments:

dic 22, 2015 10:24:03 AM org.apache.catalina.core.AprLifecycleListener init
Informazioni: Loaded APR based Apache Tomcat Native library 1.1.29 using APR version 1.4.8.
dic 22, 2015 10:24:03 AM org.apache.catalina.core.AprLifecycleListener init
Informazioni: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
dic 22, 2015 10:24:04 AM org.apache.catalina.core.AprLifecycleListener initializeSSL
Informazioni: OpenSSL successfully initialized (OpenSSL 1.0.1e 11 Feb 2013)
dic 22, 2015 10:24:04 AM org.apache.coyote.AbstractProtocol init
Informazioni: Initializing ProtocolHandler ["http-apr-80"]
dic 22, 2015 10:24:04 AM org.apache.coyote.AbstractProtocol init
Informazioni: Initializing ProtocolHandler ["ajp-apr-8009"]
dic 22, 2015 10:24:04 AM org.apache.catalina.startup.Catalina load
Informazioni: Initialization processed in 1220 ms
dic 22, 2015 10:24:04 AM org.apache.catalina.core.StandardService startInternal
Informazioni: Starting service Catalina
dic 22, 2015 10:24:04 AM org.apache.catalina.core.StandardEngine startInternal
Informazioni: Starting Servlet Engine: Apache Tomcat/7.0.42
dic 22, 2015 10:24:04 AM org.apache.catalina.startup.HostConfig deployDescriptor
Informazioni: Deploying configuration descriptor C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\conf\Catalina\localhost\o2-base-portlet.xml
dic 22, 2015 10:24:04 AM org.apache.catalina.startup.HostConfig deployDescriptor
Avvertenza: A docBase C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\o2-base-portlet inside the host appBase has been specified, and will be ignored
dic 22, 2015 10:24:04 AM org.apache.catalina.startup.SetContextPropertiesRule begin
Avvertenza: [SetContextPropertiesRule]{Context} Setting property 'source' to 'org.eclipse.jst.jee.server:o2-base-portlet' did not find a matching property.
dic 22, 2015 10:24:08 AM org.apache.catalina.startup.HostConfig deployDescriptor
Informazioni: Deploying configuration descriptor C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\conf\Catalina\localhost\ROOT.xml
dic 22, 2015 10:26:29 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\biznizz-theme
dic 22, 2015 10:26:30 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\chart-portlet
dic 22, 2015 10:26:32 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\CustomLandingPage-hook
dic 22, 2015 10:26:33 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\kaleo-web
dic 22, 2015 10:26:36 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\lcs-portlet
dic 22, 2015 10:26:38 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\liferay-vaadin-portlet
dic 22, 2015 10:26:39 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\madrid-theme
dic 22, 2015 10:26:40 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\marketplace-portlet
dic 22, 2015 10:27:09 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\notifications-portlet
dic 22, 2015 10:27:19 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\privacy-portlet
dic 22, 2015 10:27:25 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\resources-importer-web
dic 22, 2015 10:27:33 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\sync-web
dic 22, 2015 10:27:35 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\web-form-portlet
dic 22, 2015 10:27:38 AM org.apache.coyote.AbstractProtocol start
Informazioni: Starting ProtocolHandler ["http-apr-80"]
dic 22, 2015 10:27:38 AM org.apache.coyote.AbstractProtocol start
Informazioni: Starting ProtocolHandler ["ajp-apr-8009"]
dic 22, 2015 10:27:38 AM org.apache.catalina.startup.Catalina start
Informazioni: Server startup in 213960 ms
dic 22, 2015 10:31:06 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\traveler-theme
dic 22, 2015 10:31:17 AM org.apache.catalina.startup.HostConfig checkResources
Informazioni: Reloading context [/traveler-theme]
dic 22, 2015 10:31:17 AM org.apache.catalina.core.StandardContext reload
Informazioni: Reloading Context with name [/traveler-theme] has started
dic 22, 2015 10:31:20 AM org.apache.catalina.core.StandardContext reload
Informazioni: Reloading Context with name [/traveler-theme] is completed
dic 22, 2015 10:32:00 AM org.apache.catalina.startup.HostConfig deleteRedeployResources
Informazioni: Undeploying context [/resources-importer-web]
dic 22, 2015 10:32:05 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/resources-importer-web] appears to have started a thread named [liferay/hot_deploy-1] but has failed to stop it. This is very likely to create a memory leak.
dic 22, 2015 10:32:05 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/resources-importer-web] appears to have started a thread named [MultiThreadedHttpConnectionManager cleanup] but has failed to stop it. This is very likely to create a memory leak.
dic 22, 2015 10:32:05 AM org.apache.catalina.startup.HostConfig deployDirectory
Informazioni: Deploying web application directory C:\dev\liferay\6.2.3-ce-ga4\bundles\tomcat-7.0.42\tomcat-7.0.42\webapps\resources-importer-web
dic 22, 2015 10:32:28 AM org.apache.catalina.loader.WebappClassLoader loadClass
Informazioni: Illegal access: this web application instance has been stopped already.  Could not load com.liferay.portal.util.PortalUtil.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1600)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at com.liferay.resourcesimporter.util.FileSystemImporter.addApplicationDisplayTemplates(FileSystemImporter.java:225)
    at com.liferay.resourcesimporter.util.FileSystemImporter.setUpAssets(FileSystemImporter.java:1661)
    at com.liferay.resourcesimporter.util.FileSystemImporter.doImportResources(FileSystemImporter.java:1264)
    at com.liferay.resourcesimporter.util.ResourceImporter.importResources(ResourceImporter.java:47)
    at com.liferay.resourcesimporter.messaging.ResourcesImporterHotDeployMessageListener.importResources(ResourcesImporterHotDeployMessageListener.java:124)
    at com.liferay.resourcesimporter.messaging.ResourcesImporterHotDeployMessageListener.initialize(ResourcesImporterHotDeployMessageListener.java:73)
    at com.liferay.resourcesimporter.messaging.ResourcesImporterHotDeployMessageListener.onDeploy(ResourcesImporterHotDeployMessageListener.java:86)
    at com.liferay.portal.kernel.messaging.HotDeployMessageListener.doReceive(HotDeployMessageListener.java:55)
    at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
    at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:72)
    at com.liferay.portal.kernel.messaging.SerialDestination$1.run(SerialDestination.java:65)
    at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:682)
    at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:593)
    at java.lang.Thread.run(Thread.java:744)

**Comment by icarrara** [comment]
Hi @marcoscv-work  ... Good news, I think  :-)

It is not a problem about resources importer but about the screen resolution.

I deleted my previous resources-importer-web and the deploy of traveler-theme was ok without errors.

Then I created a site starting from traveler site template.

My screen is 1680x 1050:

1) When I go to the home page as Guest (without log in) the home page is empty.  I can see only the white right arrow. As soon I click on the right arrow I can start to see the animation in the home page and the other pages.

Note that the little numbers at the bottom of the page are squares and not circles as when the pages are good displayed.

2) If I reduce the browser window simulating a smaller screen the home page appears and it is complete with images and animation

3) If I go to the home page as registered user I can see the complete homepage with images and animation, it does not matter if the browser is reduced or in full screen

Please could you try to use a screen almost 1680x 1050 to reproduce this issue ?

I attached a screen-shot of the url  http://www.test-site.com/home#portlet-left0  when the browser window is in full-screen and another after I reduced the browser window

Thank you in advance for your support !

Ivano C.
![traveler-theme-1680x1050](https://cloud.githubusercontent.com/assets/2285400/11966599/10823154-a8fd-11e5-80fa-f24295774865.png)
![traveler-theme-smaller](https://cloud.githubusercontent.com/assets/2285400/11966615/1f2e72da-a8fd-11e5-8ea1-fa4e3e1c0a70.png)

**Comment by marcoscv-work** [comment]
Thanks @icarrara tomorrow I will try to find out about those problems

**Comment by marcoscv-work** [comment]
I'm going to close this issue but I will keep trying to reproduce it

**Comment by icarrara** [comment]
Thanks @marcoscv-work

I'll confirm you that all is working good only when the user is logged in.

I'm still looking for a possible cause ...

Thank you for your support !

Ivano C.
